name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - run: ./script/prepare-env
      - run: ./script/build

      - name: Create release artifact
        if: endsWith(github.ref, '/main')
        run: |
          mv dist/ game-finalfantasy6pixelremaster/
          rm -f game-finalfantasy6pixelremaster.zip
          zip -r game-finalfantasy6pixelremaster.zip game-finalfantasy6pixelremaster/

      - name: Generate release tag
        if: endsWith(github.ref, '/main')
        id: generate_release_tag
        run: |
          echo "::set-output name=release_tag::release-$(date "+%F-%H-%M")"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: endsWith(github.ref, '/main')
        with:
          tag_name: ${{ steps.generate_release_tag.outputs.release_tag }}
          files: game-finalfantasy6pixelremaster.zip
